### PR TITLE
Make GTK's approach to hiding cursors work on Mir

### LINKED ISSUE #2073: GTK on Wayland: cursor moves when it should be hidden
To reproduce:
- Open GTK app that hides cursor while typing (tested with gedit and lxterminal)
- Start typing with cursor over text area

Expected:
- Cursor disappears (as it does in Sway)

Actual:
- Cursor moves down and to the right by about one cursor size, but stays visible 

I *think* we would have noticed before if this never worked, but I don't know what broke it.

### PR DESCRIPTION
**Pull request by AlanGriffiths**
There was a logic error in WlPointer::set_cursor() that compared a pointer with an optional (both of which, unfortunately, convert to bool).

We also needed to hook into the "commit" on the corresponding surface to detect an attempt to unmap by sending a null buffer. It looks a bit messy, but fixes #2073.

(Alternative to #2078)

### CODE REVIEW

File: src/server/frontend_wayland/wl_pointer.cpp [hunk 1]
```diff
@@ -321,11 +321,28 @@ void mf::WlPointer::maybe_frame()
...
+struct CursorSurfaceRole : mf::NullWlSurfaceRole
+{
+    mf::WlSurface* const surface;
+    mf::CommitHandler* const commit_handler;
+    explicit CursorSurfaceRole(mf::WlSurface* surface, mf::CommitHandler* commit_handler) :
+        NullWlSurfaceRole(surface),
+        surface{surface},
+        commit_handler{commit_handler} {}
+
+    void commit(mir::frontend::WlSurfaceState const& state) override
```
Comment (wmww) [inline src/server/frontend_wayland/wl_pointer.cpp:333]: If `this` is destroyed before the surface, the role is not cleared and `commit()` may be called on a freed object.

Comment (wmww) [reply src/server/frontend_wayland/wl_pointer.cpp:341]: Resolved by my commit

**Review by wmww — APPROVED** [review]
LGTM
bors delegate+

**Comment by wmww** [comment]
One thing I noticed in manual testing: the cursor now flickers to the wrong position before hiding

**Comment by wmww** [comment]
I think if the cursor is unchanged, we should wait until the next commit to apply the hotspot so it's done atomically.

**Comment by AlanGriffiths** [comment]
Tweaks make sense

bors r=wmww
