### PR TITLE
When a surface is rendered acknowledge all frames that have been committed.

### LINKED ISSUE #284: libreoffice presentations via Xwayland broken
$ miral-desktop 
...
$ miral-xrun -Xwayland libreoffice --nologo --norestore --show ~/Downloads/The-state-of-Mir.odp

Expect: first slide appears and presentation works
Actual: first slide doesn't appear until focus is changed, similarly slide changes

Note: on a quick check, this is on master: 0.31.0 appears to be OK

### PR DESCRIPTION
**Pull request by AlanGriffiths**
We messed up the handling of frames in a recent refactor: this restores the correct behaviour. (Fixes #284)

### CODE REVIEW

File: src/server/frontend_wayland/wl_surface.cpp [hunk 1]
```diff
@@ -142,7 +143,7 @@ void mf::WlSurface::attach(std::experimental::optional<wl_resource*> const& buff
 
     role->visiblity(!!buffer);
 
-    pending.buffer = buffer.value_or(nullptr);
+    pending.buffer = buffer;
```
Comment (wmww) [inline src/server/frontend_wayland/wl_surface.cpp]: If a null buffer is sent, it will come through as a nullopt, but nullopt means something different in `pending` (no buffer at all), so I believe the original was correct, unless there is something I'm missing. See https://github.com/MirServer/mir/blob/6dd056a4277b79930bb6b92d16e69d0300c6af8e/src/server/frontend_wayland/wl_surface.h#L64-L68

Comment (AlanGriffiths) [reply src/server/frontend_wayland/wl_surface.cpp]: Ack. My mistake.

**Comment by AlanGriffiths** [comment]
> @wmww Looks good; sorry for breaking it in the first place.

It is a collective failure: no tests failed, and no reviewers spotted the issue either.

**Comment by AlanGriffiths** [comment]
bors r=wmww
