### PR TITLE
Defer initializing DefaultServerConfiguration::reports until any subclasses have been fully constructed. (Fixes #361)

### LINKED ISSUE #361: AsyncServerRunner fails to suppress Mir log output
> Here's what's happening:
> 
>     AsyncServerRunner::AsyncServerRunner() calls server.override_the_logger() to override the logger and suppress logging.
>     Server overrides DefaultServerConfiguration::the_logger() in Server::ServerConfiguration
> 
> But all this is outsmarted:
> 
>     DefaultServerConfiguration::DefaultServerConfiguration (indirectly) calls the_logger() in the constructor (when initializing reports), which calls the DefaultServerConfiguration version, not the overridden one.
> 

As in https://github.com/MirServer/wlcs/issues/32

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Defer initializing DefaultServerConfiguration::reports until any subclasses have been fully constructed. (Fixes #361)

### CODE REVIEW

File: src/server/report/default_server_configuration.cpp [hunk 1]
```diff
@@ -56,9 +56,9 @@ std::unique_ptr<mir::report::ReportFactory> mir::DefaultServerConfiguration::rep
     }
 }
 
-std::shared_ptr<mir::report::Reports> mir::DefaultServerConfiguration::initialise_reports()
+std::shared_ptr<mir::report::Reports> mir::DefaultServerConfiguration::initialise_reports() const
 {
-    return std::make_unique<report::Reports>(*this, *the_options());
+    return std::make_unique<report::Reports>(const_cast<DefaultServerConfiguration&>(*this), *the_options());
```
Comment (wmww) [inline src/server/report/default_server_configuration.cpp]: `const_cast`. don't like.

File: src/include/server/mir/default_server_configuration.h [hunk 2]
```diff
@@ -459,7 +459,16 @@ class DefaultServerConfiguration : public virtual ServerConfiguration
...
-    std::shared_ptr<report::Reports> const reports;
+
+    // We should to defer initializing reports until any subclasses have been
+    // fully constructed as that allows them to configure the reporting and/or
+    // logging options.
+    // So we initializing reports in the_options() which will certainly be
+    // called before starting the server. The only tricky bit is that the_options()
+    // is called when initializing reports. Hence we need a flag to avoid endless
+    // recursion.
+    bool mutable the_options_has_been_called{false};
```
Comment (wmww) [inline src/include/server/mir/default_server_configuration.h]: Seems like excessive complexity. That being said, I don't have a proposal for how to do it better.

**Comment by AlanGriffiths** [comment]
bors r=RAOF

**Comment by AlanGriffiths** [comment]
OK, I'm convinced. Something about this is breaking mir_integration_tests.TestTouchspotVisualizations.*

**Comment by AlanGriffiths** [comment]
:(

mir_integration_tests.TestTouchspotVisualizations.* still failing on 16.04

**Comment by AlanGriffiths** [comment]
Once more for added confidence:

bors try
