### PR TITLE
[NestedServer tests] setup fake input after starting the server and before using it. (Fixes #53)

### LINKED ISSUE #53: [ FAILED ] NestedServer.*_cursor_* (usually NestedServer.named_cursor_image_changes_are_forwarded_to_host)
_copied from bug [lp:1523621](https://bugs.launchpad.net/ubuntu/+source/mir/+bug/1523621)_

$ while bin/mir_acceptance_tests --gtest_filter=NestedServer.named_cursor_image_changes_are_forwarded_to_host; do :; done

fails after a few hundred iterations.

NB There two are other tests that are probably manifesting the same underlying issue:

NestedServer.can_hide_the_host_cursor
NestedServer.animated_cursor_image_changes_are_forwarded_to_host

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

File: tests/acceptance-tests/test_nested_mir.cpp [hunk 1]
```diff
@@ -338,11 +342,51 @@ class NestedMirRunner : public mtf::HeadlessNestedServerRunner
...
+                        devices_available.raise();
+                });
+
+        auto hub = server.the_input_device_hub();
+
+        auto const register_counter = mir::raii::paired_calls(
+            [&]{ hub->add_observer(counter); },
+            [&]{ hub->remove_observer(counter); });
+
+        devices_available.wait_for(5s);
```
Comment (gerboland) [inline tests/acceptance-tests/test_nested_mir.cpp]: 5 seconds? Seems a bit long.
