### PR TITLE
Lets try again: clear wl_resource implementation on destroy

### LINKED ISSUE #1438: Use-after-free in Wayland frontend
Specifically, if an exception is thrown in the constructor of a Wayland object after the base class has been initialized, The base class is immediately freed but the `wl_resource` has already been created and set up. When the resource is destroyed (likely because the client is being terminated due to the exception that was just caught), it tries to free the C++ Wayland object again. This is the cause of the problem tested in https://github.com/MirServer/wlcs/pull/158#pullrequestreview-398203895.

### PR DESCRIPTION
**Pull request by wmww**
Fixes #1438. The sequel to #1439 because it was broken (#1445) and had to be reverted (#1446). The problem was callbacks were not getting handled correctly, which I have now fixed. The root cause is tied up with messiness around our Wayland object destruction paths as better explained in #1447.

### CODE REVIEW

File: src/wayland/generated/wayland_wrapper.cpp [hunk 1]
```diff
@@ -80,6 +80,10 @@ mw::Callback::Callback(struct wl_resource* resource, Version<1>)
     }
 }
 
+mw::Callback::~Callback()
+{
+}
```
Comment (wmww) [inline src/wayland/generated/wayland_wrapper.cpp:85]: Specifically note that the generated `~Callback()` is is empty, where as in the previous PR it tried to clear the resource implementation. This is because the deletion path for objects without requests is different.

Comment (AlanGriffiths) [reply src/wayland/generated/wayland_wrapper.cpp:85]: A shame it's not the more modern C++ `= default`. :)

Comment (wmww) [reply src/wayland/generated/wayland_wrapper.cpp:85]: I considered that, but this makes the generator implementation moderately more obvious. Since this whole area is convoluted and needs to get refactored, I decided it was good enough.

**Comment by AlanGriffiths** [comment]
Looks OK, but I don't have time to test (more thoroughly than last time) before EOW.

**Comment by wmww** [comment]
That's fine. No rush.
